name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # 푸시가 발생하는 브랜치
  pull_request:
    branches:
      - main  # PR이 발생하는 브랜치

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Node.js 버전

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Deploy to Azure
        run: |
          # Azure CLI 로그인
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          # Azure App Service에 배포
          az webapp up --name <your-app-name> --resource-group <your-resource-group> --sku F1
